description:
  "Outsidekick is the best mobile personal safety app. It tracks your location when you go outdoors apon your request. If something happens it notifies your chosen emergency contacts. Outsidekick is for you and your loved ones to have peace of mind" 
keywords:
  - Personal Safety
  - Outdoors Safety
  - Peace of mind
  - Mobile Safety App
  - Location Services
